name: Python Dash Web App CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.9]
        app-path: 
          - 'beta/python/No.1'
          - 'beta/python/No.2'
          - 'beta/python/No.3'
          - 'beta/python/No.4'
          - 'beta/python/No.5'
          - 'beta/python/No.6'
          - 'beta/python/No.7'
          - 'beta/python/No.8'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Create requirements.txt
      run: |
        echo "dash" > requirements.txt
        echo "dash-bootstrap-components" >> requirements.txt
        echo "pandas" >> requirements.txt
        echo "flake8" >> requirements.txt
        echo "pytest" >> requirements.txt
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run application
      run: |
        cd ${{ matrix.app-path }}
        python3 main.py &
        sleep 10  # Wait for the server to start
        # Add a simple check to verify the server is running
        curl http://localhost:8050 || exit 1
      timeout-minutes: 1
    
    - name: Verify application startup
      run: |
        cd ${{ matrix.app-path }}
        python -c "from app import app; print('App imported successfully')"
    
    - name: Run linter
      run: |
        cd ${{ matrix.app-path }}
        flake8 app.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 app.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
